name: Orderflow template
values:
  - key: base_url
    value: 'http://127.0.0.1:8080'
  - key: trader_a_key
    value: ''
  - key: trader_a_secret
    value: ''
  - key: trader_b_key
    value: ''
  - key: trader_b_secret
    value: ''
